name: 编译构建安装文件

on:
  push:
    tags:
      - "v*"

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: 缓存 Flutter SDK
        uses: actions/cache@v3
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-cache

      - name: 下载存储库
        uses: actions/checkout@v4

      - name: 安装 Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true # 启用内置缓存

      - name: 缓存 Pub 依赖
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}

      - name: 安装 Flutter Distributor
        run: dart pub global activate flutter_distributor

      - name: 编译 iOS
        run: flutter build ios --release --no-codesign

      - name: 编译 MacOS
        run: |
          flutter build macos
          ./build_in_mac.sh

      - name: 上传产物
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifacts
          path: |
            build/ios/iphoneos/Runner.app
            build/macos/Build/Products/Release/*.app
            dist/**/*.dmg

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: 缓存 APT 包
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/linux_deps.txt') }}

      - name: 下载存储库
        uses: actions/checkout@v4

      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev locate libfuse2
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/

      - name: 安装 Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 缓存 Pub 依赖
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}

      - name: 安装 Flutter Distributor
        run: dart pub global activate flutter_distributor

      - name: 执行编译脚本
        run: |
          ./build_in_android.sh
          ./build_in_linux.sh

      - name: 上传产物
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: |
            dist/**/*.apk
            dist/**/*.aab
            dist/**/*.AppImage
            dist/**/*.deb
            dist/**/*.zip

  windows:
    runs-on: windows-latest
    steps:
      - name: 缓存 Flutter SDK
        uses: actions/cache@v3
        with:
          path: C:\hostedtoolcache\windows\flutter
          key: ${{ runner.os }}-flutter-cache

      - name: 下载存储库
        uses: actions/checkout@v4

      - name: 安装 Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 缓存 Pub 依赖
        uses: actions/cache@v3
        with:
          path: ~\AppData\Roaming\Pub\Cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}

      - name: 安装 Flutter Distributor
        run: dart pub global activate flutter_distributor

      - name: 执行 Windows 编译脚本
        run: .\build_in_windows.bat

      - name: 上传产物
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: dist/**/*.exe

  create-release:
    needs: [macos, linux, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 下载所有产物
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: 整理文件
        run: |
          mkdir release-files
          find artifacts -type f -exec cp {} release-files/ \;
          ls -lh release-files/

      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${GITHUB_REF#refs/tags/}
          files: |
            release-files/*
